# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.instructionName = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.instructionName.sizePolicy().hasHeightForWidth())
        self.instructionName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Adlam")
        font.setPointSize(20)
        font.setBold(True)
        self.instructionName.setFont(font)
        self.instructionName.setStyleSheet("background-color: rgb(143, 240, 164);\n"
"color: rgb(0, 0, 0);")
        self.instructionName.setObjectName("instructionName")
        self.horizontalLayout_2.addWidget(self.instructionName)
        self.instructionCycles = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Adlam")
        font.setPointSize(20)
        font.setBold(True)
        self.instructionCycles.setFont(font)
        self.instructionCycles.setStyleSheet("background-color: rgb(153, 193, 241);\n"
"color: rgb(0, 0, 0);")
        self.instructionCycles.setObjectName("instructionCycles")
        self.horizontalLayout_2.addWidget(self.instructionCycles)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.instructionsScroll = InstructionsScroll(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.instructionsScroll.sizePolicy().hasHeightForWidth())
        self.instructionsScroll.setSizePolicy(sizePolicy)
        self.instructionsScroll.setWidgetResizable(True)
        self.instructionsScroll.setObjectName("instructionsScroll")
        self.scrollContents = QtWidgets.QWidget()
        self.scrollContents.setGeometry(QtCore.QRect(0, 0, 384, 470))
        self.scrollContents.setObjectName("scrollContents")
        self.instructionsScroll.setWidget(self.scrollContents)
        self.verticalLayout.addWidget(self.instructionsScroll)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.mainLayout = QtWidgets.QVBoxLayout()
        self.mainLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.mainLayout.setObjectName("mainLayout")
        self.instructionsList = InstructionsList(self.centralwidget)
        self.instructionsList.setObjectName("instructionsList")
        self.mainLayout.addWidget(self.instructionsList)
        self.stepButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepButton.sizePolicy().hasHeightForWidth())
        self.stepButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.stepButton.setFont(font)
        self.stepButton.setAutoFillBackground(False)
        self.stepButton.setFlat(False)
        self.stepButton.setObjectName("stepButton")
        self.mainLayout.addWidget(self.stepButton, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.horizontalLayout.addLayout(self.mainLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.openFile = QtGui.QAction(MainWindow)
        self.openFile.setObjectName("openFile")
        self.exitApp = QtGui.QAction(MainWindow)
        self.exitApp.setObjectName("exitApp")
        self.menuFile.addAction(self.openFile)
        self.menuFile.addAction(self.exitApp)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.openFile.triggered.connect(MainWindow.load_instructions_from_system) # type: ignore
        MainWindow.instructions_loaded['QString'].connect(self.instructionsScroll.add_instructions) # type: ignore
        self.stepButton.pressed.connect(self.instructionsScroll.tomasulo_step) # type: ignore
        self.instructionsScroll.tomasulo_finalized.connect(MainWindow.tomasulo_finalized) # type: ignore
        self.exitApp.triggered.connect(MainWindow.close) # type: ignore
        self.instructionsScroll.tomasulo_step_taken['QVariantList','QVariantList'].connect(self.instructionsList.update_instructions) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.instructionName.setText(_translate("MainWindow", "Instruction"))
        self.instructionCycles.setText(_translate("MainWindow", "N° of cycles"))
        self.stepButton.setText(_translate("MainWindow", "Step"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.openFile.setText(_translate("MainWindow", "Open"))
        self.exitApp.setText(_translate("MainWindow", "Exit"))
from widgets.instructions_list import InstructionsList
from widgets.instructions_scroll import InstructionsScroll


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
